### ISSUE TITLE
failed to load fortranmagic

### ISSUE THREAD

**Issue by panshu77** [mgaitan/fortran_magic#29]
Hi I have installed fortran magic via conda successfully.  See the message below:

(test) C:\Users\xxx>conda search fortran-magic --channel conda-forge
Loading channels: done
# Name                       Version           Build  Channel
fortran-magic                    0.7          py27_0  conda-forge
fortran-magic                    0.7          py27_1  conda-forge
fortran-magic                    0.7          py34_0  conda-forge
fortran-magic                    0.7          py34_1  conda-forge
fortran-magic                    0.7          py35_0  conda-forge
fortran-magic                    0.7          py35_1  conda-forge
fortran-magic                    0.7          py36_1  conda-forge
fortran-magic                    0.7         py_1001  conda-forge

Howeve, when I use jupyter lab I failed to load it. I tried

%load_ext fortranmagic
or 
import fortranmagic

but only have the error

"ModuleNotFoundError: No module named 'fortranmagic'"

Can you help me out? Thank you very much.

**Comment by Serge3leo** [comment]
Probable bug:
`setup.py:9: version='0.6.1',`
but
`fortran magic.py:46:__version__ = '0.7'`

Workaround: 
```
$ git clone https://github.com/mgaitan/fortran_magic.git
$ cd fortran_magic
$ python setup.py install
```

**Comment by Serge3leo** [comment]
P.S.
PyPI and conda-forge contain version of fortranmagic from 2016-03-13 (15ab10c), which is incompatible with IPython 8.x

**Comment by mgaitan** [comment]
@Serge3leo if you send a PR that fix this problem I could merge and do a new release. But I'm afraid I'm not involved in this area anymore so this project is unmaintained
