### ISSUE TITLE
Number bugs

### ISSUE THREAD

**Issue by Serge3leo** [mgaitan/fortran_magic#33]
1. Python 3.12b2 remove ``imp``
```
$ pip install fortran-magic
...
Successfully installed fortran-magic-0.7.1
$ python
Python 3.12.0b2+ (remotes/origin/3.12:2b6f475db8, Jun  8 2023, 13:18:24) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import fortranmagic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/leo/opt/anaconda3/envs/tfm312/lib/python3.12/site-packages/fortranmagic.py", line 17, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
```
2. If set verbosity level by ``%fortran_config -v``, then the first magic block ``%fortran`` will have a level - 1, the second - 2, the third - 4. Similarly, the `--extra` and `--link` flags will also exponentially duplicates;
3. When changing ``%fortran_config`` flags, the changed module has the same name and, therefore, it does not reload (macOS/Linux) or is not rebuild (Windows locks DLLs). See example: ``test/test_zload_ext.py``;
4. The "enable fortran highlight" part of `load_ipython_extension()` doesn't work because it's designed for IPython 3.x. In addition, some browsers (or antiviruses) block loading "https://raw.github.com/marijnh/CodeMirror/master/mode/fortran/fortran.js "

**Comment by mgaitan** [comment]
@Serge3leo sorry for the delay. I've just published a the release. now It will be automatic each time with push a new git tag (see release.yml gh action) 

I've just send you an invitation to be a collaborator on this repo so you officially become the maintainer of this project, are you interested? please, if you want to mention it in the README or create an AUTHORS or whatever you want, go ahead.

**Comment by mgaitan** [comment]
By the way, could you make all the CI builds work and stay green?
