### ISSUE TITLE
Fortran Magic Fails on Google Colab

### ISSUE THREAD

**Issue by coatless** [mgaitan/fortran_magic#39]
## Environment

On Google Colab using:

```
Python version: 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
NumPy version: 1.26.4
```

## Reprex

<a target="_blank" href="https://colab.research.google.com/github/coatless-r-n-d/colab-notes/blob/main/08a-fortran-magic.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

## Step-by-Step

Setting up the environment with:

```python
# Install required packages
!apt-get update -qq
!apt-get install -qq gfortran
!pip install -qq fortran-magic==0.9

%load_ext fortranmagic
```

When I try to run:

```python
%%fortran -vvv
```

I'm getting: 

```python
Running...
   /usr/bin/python3 -m numpy.f2py -m _fortran_magic_7b7ac618a80fb1a0a06f96db84609f4a -c /root/.cache/ipython/fortranmagic/0af3e9f4/_fortran_magic_7b7ac618a80fb1a0a06f96db84609f4a.f90

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/numpy/f2py/__main__.py", line 5, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/numpy/f2py/f2py2e.py", line 766, in main
    run_compile()
  File "/usr/local/lib/python3.10/dist-packages/numpy/f2py/f2py2e.py", line 594, in run_compile
    build_backend = f2py_build_generator(backend_key)
  File "/usr/local/lib/python3.10/dist-packages/numpy/f2py/_backends/__init__.py", line 6, in f2py_build_generator
    from ._distutils import DistutilsBackend
  File "/usr/local/lib/python3.10/dist-packages/numpy/f2py/_backends/_distutils.py", line 3, in <module>
    from numpy.distutils.core import setup, Extension
  File "/usr/local/lib/python3.10/dist-packages/numpy/distutils/core.py", line 24, in <module>
    from numpy.distutils.command import config, config_compiler, \
  File "/usr/local/lib/python3.10/dist-packages/numpy/distutils/command/config.py", line 19, in <module>
    from numpy.distutils.mingw32ccompiler import generate_manifest
  File "/usr/local/lib/python3.10/dist-packages/numpy/distutils/mingw32ccompiler.py", line 27, in <module>
    from distutils.msvccompiler import get_build_version as get_build_msvc_version
ModuleNotFoundError: No module named 'distutils.msvccompiler'

---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)

[<ipython-input-4-a2d4d2929719>](https://localhost:8080/#) in <cell line: 1>()
----> 1 get_ipython().run_cell_magic('fortran', '-vvv', '')

3 frames

<decorator-gen-158> in fortran(self, line, cell)

[/usr/local/lib/python3.10/dist-packages/fortranmagic.py](https://localhost:8080/#) in fortran(self, line, cell)
    514                                  fflags=fflags)
    515             if res != 0:
--> 516                 raise RuntimeError("f2py failed, see output")
    517 
    518             self._code_cache[key] = module_name

RuntimeError: f2py failed, see output
```

Any thoughts as to how to address the `ModuleNotFoundError: No module named 'distutils.msvccompiler'` error?

**Comment by Serge3leo** [comment]
Probably bug Numpy 1.26.4

Numpy does not check the distutils version, and does not switch to using `meson` if necessary (`meson` is the only available build system under modern `python3.13` above).

Workaround:
```
!pip install meson charset-normalizer ninja cmake pkgconfig
```
```
%load_ext fortranmagic
%fortran_config --backend meson -v
```

See: [08a-fortran-magic.ipynb](https://colab.research.google.com/github/Serge3leo/temp-cola/blob/main/08a-fortran-magic.ipynb)

**Comment by coatless** [comment]
@Serge3leo awesome! Thank you so much for the details & workaround. I can confirm it works now on Colab with the above tweak. 

Do you by chance know any ways to make it more robust if Colab upgrades from 3.10 to 3.12? Or do I need to not worry about it for now?

**Comment by Serge3leo** [comment]
For python 3.12 and above, everything should work fine (the tests pass).

Conda-forge (anaconda, conda, mamba), which are used for testing for early versions of python, probably supports compatibility restrictions for `python`, `numpy` and `distutils'. Is it possible that this is a `colab` bug?

**Comment by Serge3leo** [comment]
All OK

**Comment by coatless** [comment]
Most likely. I'll probably add a safe guard around it.

**Comment by Serge3leo** [comment]
For 3.12 and higher, `--backend meson` is used by default. 

Such a `notebook` may have a problem if you try to run it on ancient versions of `numpy` and/or `python`.

**Comment by Serge3leo** [comment]
It is necessary, when running `%%loadext fortranmagic`, to check the `distutils` and `numpy` versions.

If the `distutils` version is too new (> ???):

- Print instructions on how to workaround the problem, for `numpy` >= 1.26;

- Give advice to update `numpy` and/or `python`.
