### ISSUE TITLE
Problem running on Windows

### ISSUE THREAD

**Issue by vdivljak** [mgaitan/fortran_magic#7]
Hi,

I have trouble running this IPython extension, while f2py seem to run just fine on command line.

I use 64bit Python on Windows 8, with 64bit Mingw packages and running f2py example on command line looks like this: https://gist.github.com/vdivljak/9142692

Trying to run same test snippet with IPython Fortran magic fails like in this notebook: http://nbviewer.ipython.org/gist/vdivljak/9142634

Command issued by your extension seem to be just right, and I can't figure where may the problem be.
Do you perhaps, or anyone else, have an idea how to resolve this?

Thanks,
Vladan

**Comment by DavidPowell** [comment]
I also experience a similar error on windows using intel fortran. From within the notebook, I can successfully run `!f2py -c myfile.f90`, but if I try using the `%%fortran` cell magic, I get the same `CompilerNotFound` exception.

Specifying `--compiler msvc` and `--fcompiler intel` (or `intelvem` etc) does not help either.
